INSERT INTO Workout_plan VALUES ('WP001', 'M0001', 'ST018', 'Strength Boost', 'Increase Strength', 'Deadlifts, Squats, Bench Press, Pull-ups', 'Active', 'Improved lifting capacity by 10%');
INSERT INTO Workout_plan VALUES ('WP002', 'M0002', 'ST002', 'Cardio Fit', 'Enhance Endurance', 'Running, Cycling, HIIT Workouts', 'Active', 'Increased running distance to 5 miles');
INSERT INTO Workout_plan VALUES ('WP003', 'M0003', 'ST016', 'Core Power', 'Strengthen Core', 'Planks, Russian Twists, Leg Raises', 'Active', 'Core strength improved significantly');
INSERT INTO Workout_plan VALUES ('WP004', 'M0004', 'ST004', 'Weight Loss', 'Lose 5kg', 'Circuit Training, Swimming, Treadmill', 'Active', 'Lost 2kg in first 3 weeks');
INSERT INTO Workout_plan VALUES ('WP005', 'M0005', 'ST008', 'Muscle Builder', 'Build Muscle Mass', 'Bicep Curls, Leg Press, Overhead Press', 'Completed', 'Visible muscle definition gained');
INSERT INTO Workout_plan VALUES ('WP006', 'M0005', 'ST008', 'Flexibility Focus', 'Improve Flexibility', 'Yoga, Pilates, Stretching', 'Active', 'Reduced muscle stiffness');
INSERT INTO Workout_plan VALUES ('WP007', 'M0007', 'ST006', 'Endurance Edge', 'Boost Stamina', 'Rowing, Long-Distance Running, Swimming', 'Active', 'Running time improved by 15%');
INSERT INTO Workout_plan VALUES ('WP008', 'M0008', 'ST008', 'Boxing Basics', 'Learn Boxing', 'Shadow Boxing, Punching Bag, Jump Rope', 'Completed', 'Improved hand speed and power');
INSERT INTO Workout_plan VALUES ('WP009', 'M0009', 'ST009', 'Power Lifts', 'Maximize Strength', 'Squats, Deadlifts, Bench Press', 'Active', 'Lifted 20% heavier weights');
INSERT INTO Workout_plan VALUES ('WP010', 'M0010', 'ST010', 'Yoga Flow', 'Enhance Flexibility', 'Vinyasa Yoga, Sun Salutations, Breathwork', 'Active', 'Increased range of motion');
INSERT INTO Workout_plan VALUES ('WP011', 'M0001', 'ST004', 'Weight Cut', 'Lose Weight', 'HIIT, Burpees, Jumping Jacks', 'Completed', 'Lost 6kg over 3 months');
INSERT INTO Workout_plan VALUES ('WP012', 'M0002', 'ST012', 'Core Stability', 'Improve Posture', 'Foam Rolling, Stretching, Core Workouts', 'Active', 'Back pain significantly reduced');
INSERT INTO Workout_plan VALUES ('WP013', 'M0003', 'ST002', 'Upper Body Strength', 'Build Upper Body', 'Bench Press, Rows, Pull-ups', 'Active', 'Shoulder and chest strength improved');
INSERT INTO Workout_plan VALUES ('WP014', 'M0014', 'ST014', 'Leg Day', 'Strengthen Legs', 'Lunges, Leg Press, Hamstring Curls', 'Completed', 'Increased leg press weight by 15%');
INSERT INTO Workout_plan VALUES ('WP015', 'M0001', 'ST006', 'CrossFit Ready', 'Get Strong and Agile', 'Kettlebells, Sprints, Olympic Lifts', 'Active', 'Better form and higher weights'),;
INSERT INTO Workout_plan VALUES ('WP016', 'M0016', 'ST016', 'Pilates Plus', 'Balance and Control', 'Core Exercises, Flexibility Training', 'Completed', 'Improved body balance');
INSERT INTO Workout_plan VALUES ('WP017', 'M0017', 'ST014', 'Boxing Pro', 'Cardio and Agility', 'Shadow Boxing, Burpees, Footwork Drills', 'Active', 'Enhanced agility and endurance');
INSERT INTO Workout_plan VALUES ('WP018', 'M0008', 'ST008', 'Weightlifting', 'Maximize Strength', 'Deadlifts, Squats, Overhead Press', 'Active', 'Improved lifting form');
INSERT INTO Workout_plan VALUES ('WP019', 'M0019', 'ST019', 'Yoga Relax', 'Relax and Stretch', 'Restorative Yoga, Breathing Exercises', 'Completed', 'Reduced stress significantly');
INSERT INTO Workout_plan VALUES ('WP020', 'M0011', 'ST018', 'Swim Power', 'Build Upper Body', 'Laps, Bodyweight Exercises, Stretching', 'Active', 'Better upper body strength');
